env:
  browser: true
  es6: true
extends: airbnb-base
globals:
  Atomics: readable
  SharedArrayBuffer: readable
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  object-curly-spacing: off
  no-multi-spaces: off
  indent: off
  no-param-reassign: off
  no-extend-native: off
  func-names: off
  no-unused-vars: warn
  no-console: off
  no-restricted-globals: off
  no-trailing-spaces: off
  no-plusplus: off
  no-alert: off
